/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ForwarderInterface extends ethers.utils.Interface {
  functions: {
    "EIP712_DOMAIN_TYPE()": FunctionFragment;
    "GENERIC_PARAMS()": FunctionFragment;
    "_getEncoded(tuple,bytes32,bytes)": FunctionFragment;
    "domains(bytes32)": FunctionFragment;
    "execute(tuple,bytes32,bytes32,bytes,bytes)": FunctionFragment;
    "getNonce(address)": FunctionFragment;
    "registerDomainSeparator(string,string)": FunctionFragment;
    "registerRequestType(string,string)": FunctionFragment;
    "typeHashes(bytes32)": FunctionFragment;
    "verify(tuple,bytes32,bytes32,bytes,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "EIP712_DOMAIN_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GENERIC_PARAMS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_getEncoded",
    values: [
      {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "domains", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerDomainSeparator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRequestType",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "typeHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "EIP712_DOMAIN_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GENERIC_PARAMS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_getEncoded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "domains", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRequestType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "typeHashes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {
    "DomainRegistered(bytes32,bytes)": EventFragment;
    "RequestTypeRegistered(bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DomainRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestTypeRegistered"): EventFragment;
}

export class Forwarder extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ForwarderInterface;

  functions: {
    EIP712_DOMAIN_TYPE(overrides?: CallOverrides): Promise<[string]>;

    "EIP712_DOMAIN_TYPE()"(overrides?: CallOverrides): Promise<[string]>;

    GENERIC_PARAMS(overrides?: CallOverrides): Promise<[string]>;

    "GENERIC_PARAMS()"(overrides?: CallOverrides): Promise<[string]>;

    _getEncoded(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_getEncoded(tuple,bytes32,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    domains(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    "domains(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    execute(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "execute(tuple,bytes32,bytes32,bytes,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    getNonce(from: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "getNonce(address)"(
      from: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerDomainSeparator(string,string)"(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerRequestType(string,string)"(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    typeHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    "typeHashes(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verify(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "verify(tuple,bytes32,bytes32,bytes,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  EIP712_DOMAIN_TYPE(overrides?: CallOverrides): Promise<string>;

  "EIP712_DOMAIN_TYPE()"(overrides?: CallOverrides): Promise<string>;

  GENERIC_PARAMS(overrides?: CallOverrides): Promise<string>;

  "GENERIC_PARAMS()"(overrides?: CallOverrides): Promise<string>;

  _getEncoded(
    req: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "_getEncoded(tuple,bytes32,bytes)"(
    req: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  domains(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "domains(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  execute(
    req: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    sig: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "execute(tuple,bytes32,bytes32,bytes,bytes)"(
    req: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    sig: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getNonce(address)"(
    from: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  registerDomainSeparator(
    name: string,
    version: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerDomainSeparator(string,string)"(
    name: string,
    version: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerRequestType(
    typeName: string,
    typeSuffix: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerRequestType(string,string)"(
    typeName: string,
    typeSuffix: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  typeHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "typeHashes(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verify(
    req: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    sig: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "verify(tuple,bytes32,bytes32,bytes,bytes)"(
    req: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    sig: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    EIP712_DOMAIN_TYPE(overrides?: CallOverrides): Promise<string>;

    "EIP712_DOMAIN_TYPE()"(overrides?: CallOverrides): Promise<string>;

    GENERIC_PARAMS(overrides?: CallOverrides): Promise<string>;

    "GENERIC_PARAMS()"(overrides?: CallOverrides): Promise<string>;

    _getEncoded(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "_getEncoded(tuple,bytes32,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    domains(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "domains(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    execute(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; ret: string }>;

    "execute(tuple,bytes32,bytes32,bytes,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; ret: string }>;

    getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getNonce(address)"(
      from: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerDomainSeparator(string,string)"(
      name: string,
      version: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerRequestType(string,string)"(
      typeName: string,
      typeSuffix: string,
      overrides?: CallOverrides
    ): Promise<void>;

    typeHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "typeHashes(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verify(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "verify(tuple,bytes32,bytes32,bytes,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    DomainRegistered(
      domainSeparator: BytesLike | null,
      domainValue: null
    ): EventFilter;

    RequestTypeRegistered(
      typeHash: BytesLike | null,
      typeStr: null
    ): EventFilter;
  };

  estimateGas: {
    EIP712_DOMAIN_TYPE(overrides?: CallOverrides): Promise<BigNumber>;

    "EIP712_DOMAIN_TYPE()"(overrides?: CallOverrides): Promise<BigNumber>;

    GENERIC_PARAMS(overrides?: CallOverrides): Promise<BigNumber>;

    "GENERIC_PARAMS()"(overrides?: CallOverrides): Promise<BigNumber>;

    _getEncoded(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_getEncoded(tuple,bytes32,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    domains(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "domains(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    execute(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "execute(tuple,bytes32,bytes32,bytes,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getNonce(address)"(
      from: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerDomainSeparator(string,string)"(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerRequestType(string,string)"(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    typeHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "typeHashes(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verify(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verify(tuple,bytes32,bytes32,bytes,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    EIP712_DOMAIN_TYPE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "EIP712_DOMAIN_TYPE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GENERIC_PARAMS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "GENERIC_PARAMS()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _getEncoded(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_getEncoded(tuple,bytes32,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    domains(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "domains(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    execute(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "execute(tuple,bytes32,bytes32,bytes,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    getNonce(
      from: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNonce(address)"(
      from: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerDomainSeparator(string,string)"(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerRequestType(string,string)"(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    typeHashes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "typeHashes(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verify(tuple,bytes32,bytes32,bytes,bytes)"(
      req: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
