/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IForwarderInterface extends ethers.utils.Interface {
  functions: {
    "execute(tuple,bytes32,bytes32,bytes,bytes)": FunctionFragment;
    "getNonce(address)": FunctionFragment;
    "registerDomainSeparator(string,string)": FunctionFragment;
    "registerRequestType(string,string)": FunctionFragment;
    "verify(tuple,bytes32,bytes32,bytes,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "execute",
    values: [
      {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerDomainSeparator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRequestType",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRequestType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export class IForwarder extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IForwarderInterface;

  functions: {
    execute(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "execute(tuple,bytes32,bytes32,bytes,bytes)"(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    getNonce(from: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "getNonce(address)"(
      from: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerDomainSeparator(string,string)"(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerRequestType(string,string)"(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    verify(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "verify(tuple,bytes32,bytes32,bytes,bytes)"(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  execute(
    forwardRequest: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    signature: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "execute(tuple,bytes32,bytes32,bytes,bytes)"(
    forwardRequest: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    signature: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getNonce(address)"(
    from: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  registerDomainSeparator(
    name: string,
    version: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerDomainSeparator(string,string)"(
    name: string,
    version: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerRequestType(
    typeName: string,
    typeSuffix: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerRequestType(string,string)"(
    typeName: string,
    typeSuffix: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  verify(
    forwardRequest: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "verify(tuple,bytes32,bytes32,bytes,bytes)"(
    forwardRequest: {
      from: string;
      to: string;
      value: BigNumberish;
      gas: BigNumberish;
      nonce: BigNumberish;
      data: BytesLike;
    },
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    execute(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; ret: string }>;

    "execute(tuple,bytes32,bytes32,bytes,bytes)"(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; ret: string }>;

    getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getNonce(address)"(
      from: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerDomainSeparator(string,string)"(
      name: string,
      version: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerRequestType(string,string)"(
      typeName: string,
      typeSuffix: string,
      overrides?: CallOverrides
    ): Promise<void>;

    verify(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "verify(tuple,bytes32,bytes32,bytes,bytes)"(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    execute(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "execute(tuple,bytes32,bytes32,bytes,bytes)"(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getNonce(address)"(
      from: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerDomainSeparator(string,string)"(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerRequestType(string,string)"(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    verify(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verify(tuple,bytes32,bytes32,bytes,bytes)"(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "execute(tuple,bytes32,bytes32,bytes,bytes)"(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    getNonce(
      from: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNonce(address)"(
      from: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerDomainSeparator(string,string)"(
      name: string,
      version: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerRequestType(string,string)"(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    verify(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verify(tuple,bytes32,bytes32,bytes,bytes)"(
      forwardRequest: {
        from: string;
        to: string;
        value: BigNumberish;
        gas: BigNumberish;
        nonce: BigNumberish;
        data: BytesLike;
      },
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
